services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual.
    build: .
    # Define um nome para o contêiner para facilitar a identificação.
    container_name: app
    # Mapeia a porta 8000 do host para a porta 8000 do contêiner.
    ports:
      - "8000:8000"
    # Monta o diretório atual no contêiner em /app.
    # Isso permite que as alterações no código sejam refletidas
    # instantaneamente (hot-reload) e que o banco de dados SQLite
    # (`escola.db`) seja persistido na máquina host.
    volumes:
      - .:/app
    # Sobrescreve o comando padrão para executar o Uvicorn com hot-reload.
    # O host 0.0.0.0 torna a aplicação acessível de fora do contêiner.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

